Solved MeetupCover с v-bind
js-tasks-ru/vue-20220125_alal111 pull request #5
Opened 2022-02-02 09:37 UTC by AlexanderBredun

2022-02-02 09:38 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-08 08:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-08 11:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-08 12:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 09:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 11:00 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 11:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 12:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-09 21:12 UTC, ShGKme requested changes
В `01-VBindCover` требуется поправить вывод фона.

В `04-vue-cli/02-TheToaster` не использовать `Date` как уникальный идентификатор.

В `04-vue-cli/03-UiDropdown1` требуется сделать `hasIcons` вычисляемым свойством, а не вычислять на этапе инициализации компонента для поддержки обновления параметра.

Все остальные задачи приняты,

2022-02-09 21:12 UTC, ShGKme commented on 03-sfc/01-VBindCover/components/MeetupCover.vue
> +   /*background-image: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), var(--default-cover);*/
Сейчас выводится всегда три фона:
1. Градиент затемнения
2. Картинка по ссылке
3. Картинка по умолчанию

При этом и 2 и 3 выводятся всегда, и когда изображение есть, и когда изображения со ссылкой нет, а в стилях остаётся только `url('undefiend')`. В итоге визуально работает, но это некорректные стили.

Требуется выводить либо картинку по ссылке, либо фон по умолчанию, в зависимости от наличия картинки.

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Под добавления тоста дублируется почти одинаковый во всех трёх методах. Лучше вынести его в универсальный метод с параметрами.

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Лучше не использовать время (`Date`) в качестве идентификатора. Не гарантируется его уникальность. Вместо времени может быть инкрементный идентификатор (просто делать `lastId++` на уровне модуля компонента), или случайный (`nanoid`, `uuid`).

Да, кликать несколько раз в миллисекунду пользователь не будет, но тосты могут добавляться и программно. Тогда возможно добавление сразу двух тостов за одну мс.

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</style>
👍

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      }, time);
Во Vue в компонентах с его данными мы можем использовать мутацию данных, как захотим. Например, когда требуется удалить элемент массива, можно не создавать новый массив на основе фильтрации без одного элемента от старого, а удалить только один этот элемент через `findIndex` + `splice`. Это позволит не создавать новый массив лишний раз.

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Вычисляемое свойства - это именно свойства. Для них описывается функция, с помощью которой Vue будет вычислять значение вычисляемого свойства, но оно остаётся свойством. По этой причине вычисляемые свойства принято называть, как свойства, а не как функции (не с глагола, без get).

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`hasIcons` - не самостоятельные данные компонента, а результат вычисления от `options`. Лучше делать его вычисляемым свойством. В этом случае решение ещё и будет поддерживать обновления списка вариантов. Текущее решение считает, что `options` не может меняться, а список вариантов константный.

2022-02-09 21:12 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Кстати, `some` итак возвращает `Boolean` :)

2022-02-13 14:58 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-13 15:02 UTC, AlexanderBredun commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      }, time);
а на сколько это критично? с фильтром просто это выглядит намного проще ну и меньше кода писать

2022-02-14 14:46 UTC, ShGKme approved these changes
Все задачи приняты

2022-02-14 14:46 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    <UiToast
Лишний вывод...

2022-02-14 14:48 UTC, merged